_wandb:
    value:
        cli_version: 0.25.0
        e:
            nk7p6kavohamo4hat5jm2gs1axak4z84:
                codePath: demo.py
                codePathLocal: demo.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "510770802688"
                        used: "359260762112"
                email: dbatbold@ucsc.edu
                executable: C:\Python314\python.exe
                git:
                    commit: a8b59131739842b66aacbee277c6c059518650b8
                    remote: https://github.com/firebreaker123/CMPM-17-ML-Real-Waste.git
                gpu: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                      uuid: GPU-e9f24c8a-ac94-e547-7132-f7e339fdb672
                host: LAPTOP-HPMVTQ57
                memory:
                    total: "6287331328"
                os: Windows-11-10.0.26200-SP0
                program: C:\CMPM17-ML\CMPM-17-ML-Real-Waste\demo.py
                python: CPython 3.14.0
                root: C:\CMPM17-ML\CMPM-17-ML-Real-Waste
                startedAt: "2026-03-17T04:15:18.646114Z"
                writerId: nk7p6kavohamo4hat5jm2gs1axak4z84
        m: []
        python_version: 3.14.0
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
            "4": 3.14.0
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
